### ISSUE TITLE
AMD drivers have had broken OpenGL exclusive fullscreen

### ISSUE THREAD

**Issue by ghost** [ppy/osu-stable-issues#1092]
The issue has been reported by multiple users

https://osu.ppy.sh/community/forums/topics/1687857?n=1

https://osu.ppy.sh/community/forums/topics/1698154?n=1

https://osu.ppy.sh/community/forums/topics/1694400?n=1

https://osu.ppy.sh/community/forums/topics/1693283?n=1

https://osu.ppy.sh/community/forums/topics/1669848?n=1

https://osu.ppy.sh/community/forums/topics/1654391?n=1

Exclusive fulscreen works on 
1: AMD drivers 22.5.1
2: compatibility mode (but has issues with alt tabbing)
3: Amernime Zone drivers

**Comment by peppy** [comment]
Have you tested lazer? Does the same apply there?

**Comment by ghost** [comment]
Works perfectly fine in lazer

**Comment by jjhhgg100123** [comment]
Going to bump this issue and add some more details.

Newer versions of AMD Drivers (unsure which specific one) seemed to fix driver crashes I was getting when booting the game, but instead trade it for a black flash at the beginning of maps, which can easily cause a missed circle. It's not consistent, but once it starts in a session it doesn't stop until a game restart. What seems to frequently trigger it is either alt-tabbing or using the boss key

Driver version 22.5.1  and before (pre AMD OpenGL changes) are safe, and post are varying levels of broken, ranging from crashing in the earlier ones to just the black screens in later ones. Personally I'm running Windows 10.

While this likely isn't osu!'s problem specifically and more on AMD's end, a workaround outside of using compatibility mode would be nice as the improvements in newer driver versions see a lot of bug fixes and in some cases 100%+ improvements in perf in other OpenGL games.

**Comment by 0x84f** [comment]
I have the same issue, for me it's a stutter when the first slider of the map is shown on screen. I would play a map, finish it, tab out to check something, tab back in and start a new map and the issue just repeats again and again. 
And yes, lazer works fine and doesn't have this issue.

I tried reinstalling drivers several times, reinstalled Windows several times as well due to another AMD bug ruining my Windows install, but no luck with this at all.

GPU specs:
AMD Radeon 5700XT (driver ver. 23.4.3)

Let me know what logs you require and I can send them in.

**Comment by SzefRon** [comment]
I have investigated the blinking issue on first slider appearance
and in my case the "snaking sliders" option seems to be causing it.

After turning it off the blinking stopped.
(Radeon RX 570 here)

It's kind of funny how specific this driver issue seems to be xD

**Comment by smoogipoo** [comment]
I was initially able to repro this on our new test bench, but I am no longer able to. Can you confirm whether it still happens?

**Comment by its0ka** [comment]
https://github.com/ppy/osu-stable-issues/issues/412 duplicate, how the hell only nvidia did it right?


> Exclusive fulscreen works on
> 3: Amernime Zone drivers

only with legacy opengl selected

please report here so they fix it faster, im so tired of this https://community.amd.com/t5/opengl-vulkan/amd-drivers-have-had-broken-opengl-exclusive-fullscreen-for/m-p/572347
it breaks not so often on newest drivers, i just need to be very careful with alt+tabbing.

this is not the only issue on amd gpu, my game crashes often when i play maps with videos, screen flicker and mess my input when first slider appear after alt+tab...

**Comment by jjhhgg100123** [comment]
> I was initially able to repro this on our new test bench, but I am no longer able to. Can you confirm whether it still happens?

I can confirm it still happens on AMD Driver 23.5.1. Had the game open and alt tabbed to a browser for maybe 3m or so, and I am getting the black flashes at the start of a map. W10, 6900XT, latest driver (23.5.1).

**Comment by 0x84f** [comment]
I just updated my drivers to 23.5.1 and I can also confirm the issue is still present

**Comment by its0ka** [comment]
@jjhhgg100123 @0x84f run RivaTuner Statistics Server in background to get rid of black flashing
![image](https://github.com/ppy/osu-stable-issues/assets/125186204/24338c3b-c807-4727-b249-27baab3ef572)

**Comment by its0ka** [comment]
@jjhhgg100123 why dislike? it doesn't work for you? comment instead because i didn't get email. another way of solving is enabling compatibility mode with "disable fullscreen optimizations" in osu.exe compatibility properties (required for partial alt+tab fixing, it's still bugged and peppy doesn't care, sadly). btw even with compatibility mode videos sometimes crash osu. (it feels like peppy disappears every time after hearing that it works fine in lazer, without closing the issue or making a comment, giving me a false hope that it will someday be fixed in stable)

**Comment by jjhhgg100123** [comment]
> @jjhhgg100123 why dislike? it doesn't work for you? comment instead because i didn't get email. another way of solving is enabling compatibility mode with "disable fullscreen optimizations" in osu.exe compatibility properties (required for partial alt+tab fixing, it's still bugged and peppy doesn't care, sadly). btw even with compatibility mode videos sometimes crash osu. (it feels like peppy disappears every time after hearing that it works fine in lazer, without closing the issue or making a comment, giving me a false hope that it will someday be fixed in stable)

Because workarounds are known and that's at best a bad workaround when one is built in to the game and listed in the post already. It's not helpful to the GitHub issue and pushes outside programs when you can just use compatibility mode. The most this issue needs is checking if the problem exists on new drivers as they release (because this is probably an AMD issue), and if someone on the osu team investigates it (which yes, is unlikely as they understandably have limited bandwidth), then they can ask more info. It prevents email spam/github notification spam. Also, needlessly attacking people does not cause more work to get done when the people doing the work are too busy.

**Comment by smoogipoo** [comment]
This issue is still on our radar, but due to it being a driver issue and with osu-stable doing things in completely non-standard ways, it's not easy to fix.

**Comment by its0ka** [comment]
> Because workarounds are known and that's at best a bad workaround

is my workaround really that bad? its just installing the program, setting it up and forgetting about it, doesn't harm anything except your email count and might help someone.

With compatibility mode you lose FPS and get alt+tab issues, with old/amernime zone drivers there is even more crashes if you play with video, also less fps.

**Comment by 0x84f** [comment]
Apparently this has been [fixed internally by AMD](https://community.amd.com/t5/opengl-vulkan/amd-drivers-have-had-broken-opengl-exclusive-fullscreen-for/m-p/614389/highlight/true#M4763), I will report back once the driver has been released

**Comment by 0x84f** [comment]
New AMD driver did not resolve the issue but I can see it's already mentioned on the AMD thread, so waiting on them again

**Comment by ghost** [comment]
as if they are ever gonna fix anything :(

**Comment by ghost** [comment]
misinput

**Comment by 0x84f** [comment]
Looks to be even worse now with 23.7.2, attached video of phone screen recording because OBS doesn't catch the flickering

https://github.com/ppy/osu-stable-issues/assets/24534022/672959f8-a5fe-4535-b6d2-66b0573f8106

**Comment by Sequ28** [comment]
> Looks to be even worse now with 23.7.2, attached video of phone screen recording because OBS doesn't catch the flickering
> 
>  VID_20230726_132245.mp4

oh man, I feel hopeless and stuck with 22.5.1 just to play osu! without problems... I'm gonna cry T^T

**Comment by joselithx98p** [comment]
While i was trying to open Afterburner for monitoring my pc temps I have found accidentally a fix that work for me on two diferents windows 11, if anyone can try this and tell if this works for him too on windows 10 or 11 it would be very helpful and yes, the game is on Fullscreen

The first thing to do is install the version 23.7.2 of Adrenalin (I recommend use DDU for clean all previos drivers files and do a clean installation), install MSI Afterburner and do exactly what I've done in the video

IMPORTANT: Before do the part that is in the video make sure that is disable "Minimize on alt-tab during Fullscreen" in osu settings and that Osu is added like a game in Adrenalin game section, if it isn't just add it manually, this is why i have used v23.7.2, because it recognize Osu automatically like a game, not like previous drivers versions that you have to add it manually

https://youtu.be/x7olaZ4HpYA

Sorry for my bad aim with mouse, I'm a lefty tablet player XD

PD 1: Open MSI Afterburner exactly when Osu is opening like in the video, not before or after, and don't press the "Yes" confirmation until the song start to play in the same part that is in the video (After the "Welcome to Osu", just when the music starts to play), minimize MSI Afterburner and wait for the Radeon Overlay to apear, don't click anything in the Osu window until the Radeon overlay appears, once the overlay appears now just close MSI Afterburner and its done, now you can use everything of the Radeon software, like recording, streaming and all this things, and sorry if my English is weird, i hope you understand what i trying to say XD

PD 2: For the moment I just tried it with the 23.7.2 version on windows 11, i will try it with different versions of Adrenalin in windows 11 and 10, and update this thread for what other versions this bug works

**Comment by 0x84f** [comment]
I have both lazer and stable installed and I can only have lazer show up, if I try to add stable's exe into the "Games" tab it just labels it as lazer.
![image](https://github.com/ppy/osu-stable-issues/assets/24534022/7ba8fe5b-96a3-4141-99c4-c63b7e481aa2)
So it appears that Adrenaline cannot distinguish the 2 game versions, but dunno how much that would affect this issue.

**Comment by joselithx98p** [comment]
@0x84f Just select OSU lazer that is recognized in adrenaline, select delete and add manually the normal, maybe the logo look like the OSU Lazer one, but it will be Osu normal client

**Comment by joselithx98p** [comment]
@0x84f Are you using the V23.7.2?

Edit: Try this to add osu, maybe this work: https://youtu.be/fOTFRgTjTcY

I just tested it and you can do it without the game added to "Games" and it won't affect the results, only the Radeon overlay won't show up and basically it won't going to recognize that you are playing (you can't be able to use Radeon Anti lag, Radeon Chill, Radeon Image sharpening, etc..), but the black screens will disappear 

I recommend try to add the game for use this features, but if you can't do what I do in the video just do it without the game added to Radeon

**Comment by joselithx98p** [comment]
> While i was trying to open Afterburner for monitoring my pc temps I have found accidentally a fix that work for me on two diferents windows 11, if anyone can try this and tell if this works for him too on windows 10 or 11 it would be very helpful and yes, the game is on Fullscreen
> 
> The first thing to do is install the version 23.7.2 of Adrenalin (I recommend use DDU for clean all previos drivers files and do a clean installation), install MSI Afterburner and do exactly what I've done in the video
> 
> IMPORTANT: Before do the part that is in the video make sure that is disable "Minimize on alt-tab during Fullscreen" in osu settings and that Osu is added like a game in Adrenalin game section, if it isn't just add it manually, this is why i have used v23.7.2, because it recognize Osu automatically like a game, not like previous drivers versions that you have to add it manually
> 
> https://youtu.be/x7olaZ4HpYA
> 
> Sorry for my bad aim with mouse, I'm a lefty tablet player XD
> 
> PD 1: Open MSI Afterburner exactly when Osu is opening like in the video, not before or after, and don't press the "Yes" confirmation until the song start to play in the same part that is in the video (After the "Welcome to Osu", just when the music starts to play), minimize MSI Afterburner and wait for the Radeon Overlay to apear, don't click anything in the Osu window until the Radeon overlay appears, once the overlay appears now just close MSI Afterburner and its done, now you can use everything of the Radeon software, like recording, streaming and all this things, and sorry if my English is weird, i hope you understand what i trying to say XD
> 
> PD 2: For the moment I just tried it with the 23.7.2 version on windows 11, i will try it with different versions of Adrenalin in windows 11 and 10, and update this thread for what other versions this bug works

Fix Update: It was simpler than what i wrote previously, just Run an application with admin permission just when the Osu logo appears while is opening, no matter which application, you only need the permission window to appear, and press "No" after sound the "Welcome to Osu" just when the music start to play, Click one time the Osu window and wait for the overlay to apear, and is fixed, say goodbye to all this black screens

It will work if the game is not added to Radeon Adrenalin software, but the overlay box wont appear, and maybe you have a little bit of input lag this way, I recommend add the game to "Games" tab of Radeon and enable Radeon Anti-lag for better results
If Radeon doesn't let you add the game or recognizes only osu lazer try this: (maybe you need to erase the Lazer from Games Tab of Adrenalin before do this): https://youtu.be/fOTFRgTjTcY
If after try this still doesn't let you add the game use DDU for uninstall drivers and install version 23.7.2 or 23.7.1 driver and automatically the game has to be added on the "Games" tab after a clean installation of this versions (with previous versions you will have to add it manually after a clean installation)

Here is my configuration for DDU (i know NVidia and Intel doesn't matter, but anyways i selected them just to make sure to delete anything related to GPUs drivers): https://imgur.com/wReFoBV

Problem Example: https://youtu.be/GFB4HbVdFZE
Fix with the game Added to Adrenalin: https://youtu.be/Sk3_-5wIslc
Fix without the game Added to Adrenalin: https://youtu.be/G_f0ic2s9w0

At the moment I tried this from version 22.11.2 to 23.7.2 and it works on all these versions

**Comment by a0193143** [comment]
Another temporiry solution: Switch to Comaptibility mode (osu! would run in DirectX9 instead of OpenGL) or disable Fullscreen mode.

**Comment by 0x84f** [comment]
Issue is still present in 23.8.1

As for what @joselithx98p said, I appreciate the effort you put into this but I am not downloading MSI Afterburner and going through convoluted workarounds just to play osu!, this needs to resolved through either the osu! team or the OpenGL team (I am leaning more heavily onto the OpenGL team).

EDIT: for people not in the osu!dev discord, [peppy has said they are actively reporting feedback to AMD](https://discord.com/channels/188630481301012481/1097318920991559880/1145768294461222953)
![image](https://github.com/ppy/osu-stable-issues/assets/24534022/38330b0b-fd0f-4916-9d4c-97702bb2fd97)

**Comment by smoogipoo** [comment]
We have indeed reported the issue to AMD via their internal tracker, with several reproductions including in lazer. They've since forwarded the issue to their GL dev team and we're now waiting for a response/fix. There's nothing that we can do on our side.

**Comment by Sequ28** [comment]
So guys, I've been checking here for a while now and there's no update to the new driver testing on osu! But now, I gave my effort to test the new driver AMD 23.9.1 since I've thought (Hmm it's a major release) But yeah! I've got back to 22.5.1 just now again, and the issue still persist on 23.9.1 the latest one available. So, don't waste your time if you still prioritize osu!'s consistency and stabilities and stay on 22.5.1. I've really hoped that it's fixed but it isn't. Thanks for reading! ♥

**Comment by 0x84f** [comment]
appears to be fixed on 23.9.2, at least I don't have any issues anymore
edit: nvm the game stutters/goes to black when the first slider loads, however the horrible flashing from my video example is no longer present

**Comment by Sequ28** [comment]
> appears to be fixed on 23.9.2, at least I don't have any issues anymore edit: nvm the game stutters/goes to black when the first slider loads, however the horrible flashing from my video example is no longer present

So, you think that the 23.9.2 is better than 23.9.1 in-general when it comes to osu?

**Comment by a0193143** [comment]
> edit: nvm the game stutters/goes to black when the first slider loads, however the horrible flashing from my video example is no longer present

@0x84f I didn't see any such this problem on my 5600XT with 23.9.2.

**Comment by 0x84f** [comment]
> > appears to be fixed on 23.9.2, at least I don't have any issues anymore edit: nvm the game stutters/goes to black when the first slider loads, however the horrible flashing from my video example is no longer present
> 
> So, you think that the 23.9.2 is better than 23.9.1 in-general when it comes to osu?

yes, relating to the issues i showed above in my video

**Comment by Sequ28** [comment]
> > edit: nvm the game stutters/goes to black when the first slider loads, however the horrible flashing from my video example is no longer present
> 
> @0x84f I didn't see any such this problem on my 5600XT with 23.9.2.

I've updated to 23.9.2 and seems that the issue represented by 0x84f is not presented to me. Note: I did fresh install of the driver and it's more less latency than the 22.5.1 and 23.9.1, I like the experience and I'm staying in the latest one. It's so responsive to the point where my pentab has no latency, at all. So maybe, this kind of particular issue persist to some of the people only

**Comment by jjhhgg100123** [comment]
> > > edit: nvm the game stutters/goes to black when the first slider loads, however the horrible flashing from my video example is no longer present
> > 
> > 
> > @0x84f I didn't see any such this problem on my 5600XT with 23.9.2.
> 
> I've updated to 23.9.2 and seems that the issue represented by 0x84f is not presented to me. Note: I did fresh install of the driver and it's more less latency than the 22.5.1 and 23.9.1, I like the experience and I'm staying in the latest one. It's so responsive to the point where my pentab has no latency, at all. So maybe, this kind of particular issue persist to some of the people only

That sounds like placebo and if you're looking in the bottom right that is not latency, it's frametimes. The issue also takes specific conditions to trigger that you might just not hit. There are still multiple reported cases, so it's clearly not fixed and at most improved.

**Comment by Sequ28** [comment]
> > > > edit: nvm the game stutters/goes to black when the first slider loads, however the horrible flashing from my video example is no longer present
> > > 
> > > 
> > > @0x84f I didn't see any such this problem on my 5600XT with 23.9.2.
> > 
> > 
> > I've updated to 23.9.2 and seems that the issue represented by 0x84f is not presented to me. Note: I did fresh install of the driver and it's more less latency than the 22.5.1 and 23.9.1, I like the experience and I'm staying in the latest one. It's so responsive to the point where my pentab has no latency, at all. So maybe, this kind of particular issue persist to some of the people only
> 
> That sounds like placebo and if you're looking in the bottom right that is not latency, it's frametimes. The issue also takes specific conditions to trigger that you might just not hit. There are still multiple reported cases, so it's clearly not fixed and at most improved.

Actually my point is that I feel less input-delay on my peripherals, also I'm aware that it's frametime, so lower means better. You know what I mean? XD

**Comment by a0193143** [comment]
> I've updated to 23.9.2 and seems that the issue represented by 0x84f is not presented to me. Note: I did fresh install of the driver and it's more less latency than the 22.5.1 and 23.9.1, I like the experience and I'm staying in the latest one. It's so responsive to the point where my pentab has no latency, at all. So maybe, this kind of particular issue persist to some of the people only

I think this due to AMD changed some behavior about OpenGL rendering after 22.5.1.
On 22.5.1 and before, osu! with vsync is almost unplayable, unstable fps and huge input lag (5 frames, would be 83ms on 60Hz monitor), but if toggled on the option "Reduce dropped frames", osu! would become very smooth.
After 22.5.1, the "Reduce dropped frames" option would does nothing, but osu! experience is same as 22.5.1 toggled on.

Here's the Frame time display graphs.
22.5.1 w/o Reduce dropped frames
![old_off](https://github.com/ppy/osu-stable-issues/assets/32773311/58073c82-b90b-45fe-b117-58908276fb92)

22.5.1 w/ Reduce dropped frames
![old_on](https://github.com/ppy/osu-stable-issues/assets/32773311/8eefc00f-6e72-41b6-aeae-c719740ffdcc)

After 22.5.1
![new](https://github.com/ppy/osu-stable-issues/assets/32773311/e1372f29-a0da-46fa-a362-9f65ba1ce6c4)

**Comment by RedoxOSU** [comment]
AMD drivers version 23.11.1. Full screen still has the first slider flicker every time a new beatmap is played. It seems to be occurring randomly.

**Comment by Sequ28** [comment]
> AMD drivers version 23.11.1. Full screen still has the first slider flicker every time a new beatmap is played. It seems to be occurring randomly.

Thank you for continuing testing for the osu! community, we really needed those updates and I myself will also provide updates time by time ^^

**Comment by Trilinear** [comment]
As of the 20231120.4 Cutting Edge update, it seems that first slider flicker is no longer there for me regardless of where I alt-tab in-game. Screenshots also don't flicker anymore, and this is with AMD drivers 23.11.1 on an RX580.

**Comment by dedocne** [comment]
As of the Cutting Edge 20231120.4 update, the flickering on screenshots and the first slider seems to have gone away, regardless of where you alt-tab. I would like others to do some more testing on Cutting Edge, but as far as I can tell, it is gone for me. This was on an RX580 with the 23.11.1 drivers.

**Comment by peppy** [comment]
Glad to hear you've seen an improvement. We kinda managed to half-fix the issue via an unrelated fix, and I added some jank workaround to cover the remaining cases.

**Comment by ghost** [comment]
Dont notice any more flickering  on my rx590 with the latest drivers, thank you

**Comment by cya-n** [comment]
Flickering issue is also gone from my end (RX 6600, 23.11.1 drivers) thanks for the update <3

**Comment by peppy** [comment]
Thanks for all the feedback. Will tentatively close this.

Do note that we are still using a dodgy workaround so it may break in the future. Feel free to reply and bump this issue thread if it occurs again.
