### ISSUE TITLE
Changing offset (global or local) causes sudden 'timing snap' at the beginning of a map

### ISSUE THREAD

**Issue by percyqaz** [ppy/osu-stable-issues#3]
To replicate:
- Take a beatmap (most clearly visible on mania) where the first note begins very close to 0ms into the audio file
- Change the game offset either locally or globally by about 100ms to make the effect visible
- The hit objects will appear with no offset applied during the lead-in time before the audio
- When the audio starts playing, the sync is applied causing mania notes to jump massively up/down (may affect osu!standard approach circles and such but I don't have any experience with this happening)

If you can't replicate this or need an example I can make a video clip illustrating this
The fix should just be to also apply the offset to the lead-in timer before audio starts playing (I experienced and patched this bug working on my own rhythm game project, and it was because I used a Timer to pad the time before the first note appeared to give at least 2 seconds of time after pressing "play". I'm assuming a similar strategy is used here, and the Timer is not having the offset applied)

Hopefully this explanation makes it possible to track this down.
I must stress that this bug is REALLY annoying on affected osu!mania map as it makes it nearly impossible to time the first notes.

**Comment by percyqaz** [comment]
Update: here is a good example map
https://osu.ppy.sh/beatmapsets/672291#mania/1421154

**Comment by peppy** [comment]
Can you confirm what your Universal Offset is set to?

**Comment by percyqaz** [comment]
Currently 0 but I have changed it to both positive and negative values to confirm it has the same effect as, and stacks with, local offset. I used to play with +20ms for a while and had this issue.
On the chart provided I have -10ms set as my local offset which causes a minor but distracting bump at scroll speed 27

**Comment by peppy** [comment]
This is caused by the switch between virtual and audio-driver based time. It's already resolved in lazer via some more [complex logic](https://github.com/ppy/osu/pull/4883). I'll take a 5 minute look into this one, but I'm not sure it's an easily solvable one.

**Comment by SupertCZ** [comment]
This is a problem even on osu!standard, because it makes some maps hard to predict. For example this https://osu.ppy.sh/beatmapsets/746506#osu/1573321 with offset -15ms and the first note is hardly predictable.

**Comment by cakiya** [comment]
i too have this issue! it makes the first second of some maps really darn hard **(especially DT/high AR maps)**

annother example: https://osu.ppy.sh/beatmapsets/881764#osu/1844417
(snow halation reform's extra)

play the first second on DT (no hidden) without offset, then with -300ms offset. notice how it's kinda impossible to SS the first second of the map unless you retry 15 times or are good at jumpscare approach circles!!

realistically I don't think anyone is going to use -300ms offset but I use -180ms (no hitsounds; airpods pro) and it's still noticeable. peppy pls fix!

**Comment by GhostO-086** [comment]
This issue still exists. I use -110ms global offset and the mania notes will suddenly jump down when the audio start. plz fix it!

**Comment by Sircachetes** [comment]
I'm not sure if it's appropriated to comment on a post like this but this issue still happens and is very annoying. I'd appreciate it A LOT if it got fixed

**Comment by peppy** [comment]
We hope to fix this on lazer eventually. It's not a simple one.

**Comment by GhostO-086** [comment]
> We hope to fix this on lazer eventually. It's not a simple one.

Maybe we can just add an empty measure automatically at the beginning of the map and delay the music playing by also one measure. It usually happens when there're notes right at the beginning of the music I think.

**Comment by peppy** [comment]
If only it was as easy as you say 😄

**Comment by GhostO-086** [comment]
> If only it was as easy as you say 😄

When I'm mapping I always leave one measure empty at the beginning of the beatmap (mania mode) and it'll indeed avoid the problem. This is just a humble suggestion, I'm not sure how to solve the issue elegantly in code. 
Laser is good, but there're some features in the stable that make me more like the stable for now.
Anyway thanks for you developers' hard work. Hope the issue gets resolved soon!
