### ISSUE TITLE
corrupted text for unicode characters when submitted through bss

### ISSUE THREAD

**Issue by Moeriko** [ppy/osu-stable-issues#491]
map description and source field seem to be uploaded with corrupted characters instead when uploading with bss in the editor, it started happening just from today after some update with the site. the map descriptions that is editable in bss is already showing question marks on every unicode character.

**Comment by peppy** [comment]
Could you please include an example?

**Comment by Moeriko** [comment]
https://osu.ppy.sh/beatmapsets/1197592
take my mapset as example, when i update it through BSS, the description that you can edit already made all of the unicoded and japanese characters to be "?" instead of that character. i had to edit the description manually afterwards or copy paste it from a txt that i backed up the code for description. (this means that the fault may be from the site because BSS seem to still be able to submit unicode, and it's the site that cannot handle unicode)

while i can change for description, the source field seem not to work on the site, while displaying completely fine in-game. apologies for posting this in osu-stable-issues, i thought this was issue with BSS but i noticed now that it's more of a site issue, but i hope it can be noticed and fixed~

i think the site broke something regarding the unicoding and so when BSS retrieve information from the site, it gets the mis-unicoded text in description

i'm sorry if my english is a bit confusing

**Comment by peppy** [comment]
Should be fixed now. Please update once more.

**Comment by Moeriko** [comment]
it seems like it's still the same ;u; unfortunately

**Comment by peppy** [comment]
You need to upload again.

**Comment by Moeriko** [comment]
i know, i uploaded again but problem still persist. and for some of my friend it worked but it didn't work for me and i don't know why orz

**Comment by Moeriko** [comment]
wait, does upload mean i have to reupload the whole mapset? update won't work?

**Comment by Moeriko** [comment]
ok it worked for some reason now when i updated from anotehr diff
